---
title: "p8105_hw3_zw2541"
author: "Zixu_Wang"
date: "10/5/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1

#### Read and clean the data

```{r}
library(p8105.datasets)

data("brfss_smart2010")

brfss = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  rename(state = locationabbr, county = locationdesc) %>% 
  filter(topic == "Overall Health") %>% 
  filter(response %in% c("Excellent", "Very good","Good", "Fair", "Poor")) %>% 
  mutate(response = factor(response, levels = c("Excellent", "Very good","Good", "Fair", "Poor")))
```

#### Using this dataset, do or answer the following:

(1) In 2002, which states were observed at 7 locations?

```{r}
brfss %>% 
  filter(year == "2002") %>% 
  group_by(state) %>% 
  summarize(n_location = n_distinct(county)) %>% 
  filter(n_location == "7")
```

In 2002, Connecticut, Florida, and North Carolina were observed at 7 locations.

(2) Make a “spaghetti plot” that shows the number of locations in each state from 2002 to 2010.

```{r}
brfss %>% 
  group_by(state,year) %>% 
  summarize(n_locations = n_distinct(county)) %>% 
  ggplot(aes(x = year, y = n_locations, color = state)) +
  geom_line() +
  labs(
        title = "Spaghetti Plot-Number of Locations in Each State from 2002 to 2010",
        y = "Number of locations",
        x = "Year") +
  theme(legend.position = "bottom",
        legend.key.width = unit(.25, 'cm')) +
  guides(color = guide_legend(ncol = 15))
```

